name: Build TTS App for All Platforms

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      - name: Build with PyInstaller
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            # Install required system packages for Linux
            sudo apt-get update
            sudo apt-get install -y python3-tk
            
            # Build with explicit Tcl/Tk paths
            pyinstaller --onefile \
              --strip \
              --add-binary='/usr/lib/x86_64-linux-gnu/libstdc++.so.6:.' \
              --add-data "/usr/share/tcl8.6:tk" \
              --add-data "/usr/share/tk8.6:tcl" \
              --add-data 'images:images' \
              --add-data 'UserGuide.md:UserGuide.md' \
              --collect-data ttkbootstrap \
              src/main.py

          elif [ "$RUNNER_OS" = "Windows" ]; then
            # Windows build (Tcl/Tk is auto-detected)
            pyinstaller --onefile \
              --add-data "images;images" \
              --add-data "UserGuide.md;UserGuide.md" \
              --collect-data ttkbootstrap \
              src/main.py

          else
            # macOS build
            pyinstaller --onefile \
              --add-data "$(python -c "import tkinter; print(tkinter.__file__[:-15])")/tcl8.6:tk" \
              --add-data "$(python -c "import tkinter; print(tkinter.__file__[:-15])")/tk8.6:tcl" \
              --add-data "images:images" \
              --add-data "UserGuide.md:UserGuide.md" \
              --collect-data ttkbootstrap \
              src/main.py
          fi
        shell: bash

      - name: Rename and move binary
        run: |
          mkdir -p dist-release
          if [ "$RUNNER_OS" = "Windows" ]; then
            mv dist/main.exe dist-release/TTS_App_Windows.exe
          elif [ "$RUNNER_OS" = "macOS" ]; then
            mv dist/main dist-release/TTS_App_macOS
          else
            mv dist/main dist-release/TTS_App_Linux
          fi
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TTS_App_${{ runner.os }}
          path: dist-release/*

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: dist-release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
