name: Build TTS App for All Platforms

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest] # Pinned Ubuntu version
        include:
          - os: ubuntu-20.04
            container: docker://cdrx/pyinstaller-linux:python3.10 # Compatibility-focused image

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      - name: Build with PyInstaller
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            docker run --rm -v "$(pwd):/src" ${{ matrix.container }} \
              "pyinstaller --onefile \
              --strip \
              --add-binary='/usr/lib/x86_64-linux-gnu/libstdc++.so.6:.' \
              --add-binary='/lib/x86_64-linux-gnu/libm.so.6:.' \
              --add-data 'images:images' \
              --add-data 'UserGuide.md:UserGuide.md' \
              src/main.py"
          elif [ "$RUNNER_OS" = "Windows" ]; then
            pyinstaller --onefile \
              --add-data "images;images" \
              --add-data "UserGuide.md;UserGuide.md" \
              src/main.py
          else
            pyinstaller --onefile \
              --add-data "images:images" \
              --add-data "UserGuide.md:UserGuide.md" \
              src/main.py
          fi
        shell: bash

      - name: Rename and move binary
        run: |
          mkdir -p dist-release
          if [ "$RUNNER_OS" = "Windows" ]; then
            mv dist/main.exe dist-release/TTS_App_Windows.exe
          elif [ "$RUNNER_OS" = "macOS" ]; then
            mv dist/main dist-release/TTS_App_macOS
          else
            mv dist/main dist-release/TTS_App_Linux
          fi
        shell: bash

      - name: Verify Linux compatibility
        if: runner.os == 'Linux'
        run: |
          docker run --rm -v "$(pwd)/dist-release:/app" ubuntu:18.04 /app/TTS_App_Linux --version
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TTS_App_${{ runner.os }}
          path: dist-release/*

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: dist-release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
